export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const SET_LOGIN_ATTEMPT_DETAILS = 'SET_LOGIN_ATTEMPT_DETAILS';
